# Generated by Django 3.0.5 on 2020-04-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolists',
            options={'ordering': ('id',), 'verbose_name_plural': 'To do List'},
        ),
        migrations.AddField(
            model_name='todolists',
            name='status',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
